
export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST"
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS"
export const ADD_ITEM_FAILURE = "ADD_ITEM_FAILURE"

export const SOLD_ITEM_REQUEST = "SOLD_ITEM_REQUEST"
export const SOLD_ITEM_SUCCESS = "SOLD_ITEM_SUCCESS"
export const SOLD_ITEM_FAILURE = "SOLD_ITEM_FAILURE"







